android.enableJetifier=true
android.useAndroidX=true
kapt.use.worker.api=true
kotlin.code.style=official
kotlin.incremental.multiplatform=true
kotlin.js.compiler=ir
kotlin.js.experimental.generateKotlinExternals=false
#kotlin.mpp.enableCompatibilityMetadataVariant=true
#kotlin.mpp.enableGranularSourceSetsMetadata=true
kotlin.mpp.stability.nowarn=true
#kotlin.native.enableDependencyPropagation=false
kotlin.native.enableParallelExecutionCheck=false
kotlin.setJvmTargetFromAndroidCompileOptions=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
org.gradle.jvmargs=-Xmx8G -Dfile.encoding\=UTF-8 -XX:MaxMetaspaceSize=1024m -Dkotlin.daemon.jvm.options\=-Xmx8G,-XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
systemProp.org.gradle.internal.publish.checksums.insecure=true
testOptions.unitTests.isIncludeAndroidResources=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.cacheKind=none

# supportedTargets=ios,jvm,js,wasmjs,android
firebase-analytics.supportedTargets=ios,jvm,js,wasmjs,android
firebase-app.supportedTargets=ios,jvm,js,wasmjs,android
firebase-auth.supportedTargets=ios,jvm,js,wasmjs,android
firebase-common-internal.supportedTargets=ios,jvm,js,wasmjs,android
firebase-common.supportedTargets=ios,jvm,js,wasmjs,android
firebase-config.supportedTargets=ios,jvm,js,wasmjs,android
firebase-crashlytics.supportedTargets=ios,jvm,android
firebase-database.supportedTargets=ios,jvm,js,wasmjs,android
firebase-firestore.supportedTargets=ios,jvm,js,wasmjs,android
firebase-functions.supportedTargets=ios,jvm,js,wasmjs,android
firebase-installations.supportedTargets=ios,jvm,js,wasmjs,android
firebase-messaging.supportedTargets=ios,jvm,js,wasmjs,android
firebase-perf.supportedTargets=ios,jvm,js,wasmjs,android
firebase-storage.supportedTargets=ios,jvm,js,wasmjs,android
test-utils.supportedTargets=ios,jvm,js,wasmjs,android

# supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-analytics.supportedTestTargets=js,wasmjs,android
firebase-app.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-auth.supportedTestTargets=ios,js,wasmjs,android
firebase-common-internal.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-common.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-config.supportedTestTargets=ios,js,wasmjs,android
firebase-crashlytics.supportedTestTargets=ios,android
firebase-database.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-firestore.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-functions.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-installations.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-messaging.supportedTestTargets=ios,jvm,js,wasmjs,android
firebase-perf.supportedTestTargets=ios,js,wasmjs,android
firebase-storage.supportedTestTargets=js,wasmjs,android
test-utils.supportedTestTargets=ios,jvm,js,wasmjs,android

# Version (applies to all modules):
version=0.0.2-SNAPSHOT

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
